### PR TITLE
Added databasename to the serialized items

### PR DESCRIPTION
**Pull request by csteeg**
Added databasename to the serialized items so sitecore courier can use them to create update packages

### CODE REVIEW

**Comment by csteeg** [comment]
Pretty please? :)

**Comment by kamsar** [comment]
Seems like a decent idea, I guess, if only to support Courier. However there are some things that need to be addressed:

1) Formatting using spaces for indenting. Rainbow uses tabs.
2) There needs to be provision for backwards compatibility as well as tests covering that situation. It's unreasonable to expect folks to reserialize everything for an upgrade unless there's no other way. (Or else as suggested below maybe making this an optional setting to include db?)
3) The location where the database was inserted breaks `YamlItemMetadata`'s parsing. I'm guessing that courier does not care about rapid access to metadata, so I'd suggest moving database name below all of the other metadata attributes (i.e. after Path) so that we can retain the fastest possible metadata parsing speed since that has a major effect on Unicorn performance.
4) What do you think of having the DB be an optional setting that one enables if they want it (e.g. like the other stuff in Rainbow.config)?
5) Thoughts on reducing the 'DatabaseName' string to just 'DB'?

**Comment by csteeg** [comment]
1) Sorry about that, VS hides it too good I guess :). Just committed tabified versions
2) It's backwards compatible as far as I tested it locally, I'll write a test for it.
3) noticed that already and moved it in the code, but forgot to commit the test-cases somehow. Committed now
4) also fine, but still needed if it's backwards compatible?
5) Ok, will do that as I write the tests @2

**Comment by csteeg** [comment]
Changed fieldname to db in yml and appaearently I already wrote a test for yml with and without db for backwards compatibility (where's my shortterm memory!)

**Comment by kamsar** [comment]
My thought on making it an optional setting to store the DB is that unless using courier (and self-interestedly I'm not) DB becomes irrelevant data that can be inferred from the path.

Feel free to disagree. This is a discussion not a dictatorship :)

I'll see about merging this tomorrow. Unicorn PR took my whole evening tonight and it's still not done!

**Comment by kamsar** [comment]
Merged up! I opted to make DB an on by default thing, especially in light of how I changed the namehint storage in 1.1 as well (https://github.com/kamsar/Rainbow/commit/3fe3f861a92c0a50c169f778a80ed7b861befe7a) so there are now a couple of (totally backward compatible, but you might wanna reserialize just because) format changes in the next release.

Thanks for the contribution @csteeg!

**Comment by csteeg** [comment]
Thnx for merging :)
To get back to the question: I think personally it'd be better if a .yml could be handled by any other tool (like courier) outside of the rainbow framework. Therefore I'd say the dbname should be there.

**Pull request merged**
